### ISSUE TITLE
Documentation build fails on readthedocs

### ISSUE THREAD

**Issue by MassimoCimmino** [MassimoCimmino/pygfunction#86]
Here is the log:

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygfunction/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygfunction/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygfunction/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pygfunction/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 373, in eval_config_file
    raise ConfigError(msg % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (boreholes.py, line 140)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (boreholes.py, line 140)
Command time: 0s Return: 2
```

The reference is to:
https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/boreholes.py#L140

It may also fail on the next few lines:
https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/boreholes.py#L186

**Comment by MassimoCimmino** [comment]
Another option to format the string is : `' gt.boreholes.find_duplicates() '.center(50, '-')`

I don't know why Sphinx does not like the initial implementation (it works fine on my machine).

**Comment by MassimoCimmino** [comment]
The build later failed on:
https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/media.py#L67-L68

I found that readthedocs was building the docs using Python 2, which does not support function annotations. A configuration file is introduced in [d4fa4a3](https://github.com/MassimoCimmino/pygfunction/commit/d4fa4a301afddfc184fc0e91cb79aea2c920b4dd).
